### ISSUE TITLE
RateLimiter related intermittent failures

### ISSUE THREAD

**Issue by chashikajw** [wso2/apk#1790]
**Description:**
Following intermittent issues should be fixed

**Issue1:**

```
Error 1: https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968

org.wso2.apk.integration.api.BaseSteps.setHeaders(io.cucumber.datatable.DataTable)
[863](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:864)
    | Authorization | bearer $***accessToken*** |
[864](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:865)
  And I send "GET" request to "https://default.gw.wso2.com:9095/interceptor/1.0.0/get" with body ""                   # org.wso2.apk.integration.api.BaseSteps.sendHttpRequest(java.lang.String,java.lang.String,java.lang.String)
[865](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:866)
  And the response body should not contain "\"Interceptor-Header\""                                                   # org.wso2.apk.integration.api.BaseSteps.theResponseBodyShouldNotContain(java.lang.String)
[866](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:867)
  Then the response status code should be 200                                                                         # org.wso2.apk.integration.api.BaseSteps.theResponseStatusCodeShouldBe(int)
[867](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:868)
      java.lang.AssertionError: expected [200] but found [503]
[868](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:869)
	at org.testng.Assert.fail(Assert.java:111)
[869](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:870)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
[870](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:871)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
[871](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:872)
	at org.testng.Assert.assertEquals(Assert.java:132)
[872](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:873)
	at org.testng.Assert.assertEquals(Assert.java:1419)
[873](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:874)
	at org.testng.Assert.assertEquals(Assert.java:1383)
[874](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:875)
	at org.testng.Assert.assertEquals(Assert.java:1429)
[875](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:876)
	at org.wso2.apk.integration.api.BaseSteps.theResponseStatusCodeShouldBe(BaseSteps.java:116)
[876](https://github.com/wso2/apk/actions/runs/6324929457/job/17175722968#step:11:877)
	at ✽.the response status code should be 200(file:///home/runner/work/apk/apk/apk-repo/test/cucumber-tests/src/test/resources/tests/api/Interceptor.feature:109)

```

**Issue2:**

RateLimit headers are not returning for first 1/2 requests and it returning after that. In this case the ratelimit counter is working fine from rateLimiter side.

**Comment by Tharsanan1** [comment]
Fixed with: https://github.com/wso2/apk/pull/2446
