### ISSUE TITLE
NullPointerException when getting JWT validator by Issuer

### ISSUE THREAD

**Issue by pubudu538** [wso2/apk#2210]
**Description:**
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7a0bfdbf
java.lang.NullPointerException: Cannot invoke "org.wso2.apk.enforcer.subscription.SubscriptionDataStore.getJWTValidatorByIssuer(String, String)" because the return value of "org.wso2.apk.enforcer.subscription.SubscriptionDataHolder.getSubscriptionDataStore(String)" is null
	at org.wso2.apk.enforcer.security.jwt.Oauth2Authenticator.getJwtValidationInfo(Oauth2Authenticator.java:476)
	at org.wso2.apk.enforcer.security.jwt.Oauth2Authenticator.authenticate(Oauth2Authenticator.java:136)
	at org.wso2.apk.enforcer.security.AuthFilter.authenticate(AuthFilter.java:175)
	at org.wso2.apk.enforcer.security.AuthFilter.handleRequest(AuthFilter.java:131)
	at org.wso2.apk.enforcer.api.API.executeFilterChain(API.java:42)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/apk/pull/2206
