### ISSUE TITLE
NPE in adapter

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#2497]
### Description

```
panic: runtime error: slice bounds out of range [2:1]

goroutine 29 [running]:
github.com/wso2/apk/adapter/internal/operator/synchronizer.deployMultipleAPIsInGateway(0x4000708780, 0x40001361e0)
	/Users/amali/workspace/repos/apk/adapter/internal/operator/synchronizer/synchronizer.go:153 +0x12c0
github.com/wso2/apk/adapter/internal/operator/synchronizer.HandleAPILifeCycleEvents(0x40001361d8, 0x40001361e0)
	/Users/amali/workspace/repos/apk/adapter/internal/operator/synchronizer/synchronizer.go:97 +0xdc
created by github.com/wso2/apk/adapter/internal/operator/gateway-api/provider/kubernetes.New in goroutine 65
	/Users/amali/workspace/repos/apk/adapter/internal/operator/gateway-api/provider/kubernetes/kubernetes.go:144 +0x9b8
```

### Steps to Reproduce

array index bound

### Affected Component

Adapter

### Version

latest

**Comment by AmaliMatharaarachchi** [comment]
This needs to be fixed in main branch
